#pragma config(Motor,  motorA,          m,             tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          l,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          r,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motorB] = 00;
	motor[motorC] = 1000;
	wait1Msec(8000);
}
