#pragma config(Motor,  motorA,          m,             tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          l,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          r,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		moveMotorTarget(motorB, 1250. 50);
		moveMotorTarget(motorC, 1250. 50);
		waitUntilMotorStop(motorB);
		waitUntilMotorStop(motorC);
		motor(motorB) = 50;
		motor(motorC) = 0;
		wait1Msec(820);
	}
}
