#pragma config(Sensor, S1,     t,              sensorEV3_Touch)
#pragma config(Motor,  motorA,          m,             tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          l,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          r,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		motor(motorB) = 30;
		motor(motorC) = 30;
		wait1Msec(10);

		if(SensorValue(S1) == 1)
			break;
	}

			motor(motorB) = -30;
			motor(motorC) = -30;
			playSound(soundLowBuzz);
			wait1Msec(1500);

			displayBigTextLine(8, "left");
			motor(motorB) = -40;
			motor(motorC) = 0;
			wait1Msec(1000);

	while(1){
		motor(motorB) = 30;
		motor(motorC) = 30;
		wait1Msec(10);

		if(SensorValue(S1) == 1)
			break;
	}

			motor(motorB) = -30;
			motor(motorC) = -30;
			playSound(soundLowBuzz);
			wait1Msec(1500);

			motor(motorB) = 0;
			motor(motorC) = -40;
			wait1Msec(1000);

			motor(motorB) = -30;
			motor(motorC) = -30;
			wait1Msec(2000);

}
