#pragma config(Sensor, S1,     q,              sensorEV3_Touch)
#pragma config(Sensor, S2,     w,              sensorEV3_Gyro)
#pragma config(Sensor, S3,     e,              sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     r,              sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          d,             tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          f,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          g,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	playTone(784, 1000);
	wait1Msec(1000);

	playTone(784, 1000);
	wait1Msec(1000);

	playTone(880, 1000);
	wait1Msec(1000);

	playTone(880, 1000);
	wait1Msec(1000);

	playTone(784, 1000);
	wait1Msec(1000);

	playTone(784, 1000);
	wait1Msec(1000);

	playTone(659, 1000);
	wait1Msec(1000);

}
