# print("'Hello'")
# print("\"Hello World\"")
# print("\"!@#$%^&*()'")
# print("\"C:\Download\\'hello'.py\"")
# print("print(\"Hello\\nWorld\")")
# ww = input()
# print(ww)
wew = input()
int(wew)
print(wew)