#pragma config(Sensor, S1,     T,              sensorEV3_Touch)
#pragma config(Sensor, S3,     C,              sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          A,             tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          D,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(1){
		setMotorSpeed(motorA, 5);
		wait1Msec(2500);

		moveMotorTarget(motorA, 180, -30);
		waitUntilMotorStop(motorA);

		wait1Msec(3000);
	}
}
